### ISSUE TITLE
Exiting on code 0

### ISSUE THREAD

**Issue by Thunder1723** [Didstopia/rust-server#122]
**Describe the bug**
I'm not sure what the _exact_ problem is and I've come to a complete stop with being able to figure this out.  I tried using both portainer and over a ssh window with as many configs as I could come up with for no different results.

**To Reproduce**
Attempt to run the image with docker compose on an arch machine

**Expected behavior**
The container will run for about 5 minutes getting prepared and it will close with the same errors every time in the attached log file.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Docker: 24.0.5
 - Docker Engine is operating in swarm mode
 - No plugins

**Additional context**
One of the generated log files is attached, compose and installed packages are pasted.
```
base
base-devel
dhcpcd
docker
docker-compose
efibootmgr
fail2ban
git
glusterfs
intel-ucode
linux
linux-firmware
nano
openssh
steamcmd
xf86-video-intel
zram-generator

```

```
version: '3'
services:
  rust-server:
    container_name: rust
    image: didstopia/rust-server:latest
    restart: unless-stopped
    ports:
      - 28015:28015/udp
      - 28016:28016/udp
      - 28017:28017/tcp
      - 28082:28082/tcp
    environment:
      RUST_SERVER_PORT: '28015'
      RUST_SERVER_QUERYPORT: '28016'
      RUST_SERVER_SEED: '1234567'
      RUST_SERVER_WORLDSIZE: '4250'
      RUST_SERVER_NAME: myname
      RUST_SERVER_MAXPLAYERS: '20'
      RUST_SERVER_DESCRIPTION: mydescription
      RUST_RCON_PORT: '28017'
      RUST_RCON_PASSWORD: mypassword
      RUST_APP_PORT: '28082'
      RUST_UPDATE_CHECKING: '1'
      RUST_OXIDE_ENABLED: '1'
      RUST_OXIDE_UPDATE_ON_BOOT: '1'
      RUST_RCON_SECURE_WEBSOCKET: '1'
      RUST_HEARTBEAT: '1'
    volumes:
      -  /glusterfs/Docker/Rust:/steamcmd/rust
```

[docker_2023-09-24_19-46-13.txt](https://github.com/Didstopia/rust-server/files/12709759/docker_2023-09-24_19-46-13.txt)
