### ISSUE TITLE
Login to steam failed

### ISSUE THREAD

**Issue by Steven-Harris** [Didstopia/rust-server#27]
I was trying to get my own server setup and had some issues. I can access Rcon and I was able to register my server with rust's list but I can't connect to it at all. I have port forward everything on my router and there is no other firewall in between.

I started digging in the log files and noticed this line...
```[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.``` 
I then exec'd into the container and tried logging in manually but nothing worked. For some reason ```login anonymous`` prompted for a password and didn't work. I also tried a steam account that I normally use when steamcmd requires a steam account and it didn't work either.

Here is my docker-compose: 
```
version: '3'
services:
   server:
      image: didstopia/rust-server
      ports:
       - "28015:28015"
       - "28015:28015/udp"
       - "28016:28016"
       - "8085:8080"
      volumes:
       - "./rust:/steamcmd/rust"
      environment:
       - RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load -logfile /dev/stdout +server.secure 1
       - RUST_SERVER_IDENTITY=RUST_BUCKET
       - RUST_SERVER_SEED=12345
       - RUST_SERVER_NAME=Rust Bucket
       - RUST_SERVER_DESCRIPTION=Rust Server on Tank
       - RUST_RCON_PASSWORD=${bucket_key}
       - RUST_OXIDE_ENABLED=1
```

---

### Environment (OS/Distro, Docker version etc.)
Server Version: 17.09.1-ce
