### ISSUE TITLE
Couldn't load server/docker/proceduralmap.3500.12345.172.sav - file doesn't exist

### ISSUE THREAD

**Issue by anboo** [Didstopia/rust-server#39]
**Describe the bug**
```
rust    | Monument Navmesh Build took 18.62 seconds
rust    | Map Spawned 697 entities
rust    | Couldn't load server/docker/proceduralmap.3500.12345.172.sav - file doesn't exist
rust    | Exiting...
```

**To Reproduce**
1. docker-compose up -d

**Environment (please complete the following information):**
 - OS: Linux 4.4 Ubuntu 16.04 64bit
 - Docker: Docker version 18.03.1-ce, build 9ee9f40
 - System:
```
rust    | Bootstrap Startup
rust    | CPU
rust    |       Model:  Intel(R) Atom(TM) CPU C3955 @ 2.10GHz
rust    |       Cores:  4
rust    |       Memory: 3948 MB
rust    | GPU
rust    |       Model:  Null Device
rust    |       API:    NULL 1.0 [1.0]
rust    |       Memory: 128 MB
rust    |       SM:     30
rust    | Process
rust    |       Memory:   0 MB
rust    | Mono
rust    |       Collects: 17
rust    |       Memory:   1 MB
rust    | Manifest Metadata Loaded
rust    |       12612 pooled strings
rust    |       14 mesh colliders
rust    |       5721 prefab properties
rust    |       388 effect categories
rust    |       656 entity names
rust    |       86 skinnable names
```
docker-compose.yaml:
```yaml
version: '2'

services:
  # HTTPS-ReverseProxy
  rust:
    image: blacklabelops/rust-gameserver
    container_name: rust
    ports:
      - '28015:28015'
      - '28015:28015/udp'
      - '28016:28016'
    volumes:
      - rust_data:/steamcmd/rust
    environment:
      - 'TZ=Europe/Berlin'
      - 'RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load +server.secure 1'
      - 'RUST_SERVER_IDENTITY=docker'
      - 'RUST_SERVER_SEED=12345'
      - 'RUST_SERVER_NAME=Rust Server [DOCKER]'
      - 'RUST_SERVER_DESCRIPTION=This is a Rust server running inside a Docker container!'
      - 'RUST_SERVER_URL=https://hub.docker.com/r/didstopia/rust-server/'
      - 'RUST_SERVER_BANNER_URL='
      - 'RUST_RCON_WEB=1'
      - 'RUST_RCON_PORT=28016'
      - 'RUST_RCON_PASSWORD=docker'
      - 'RUST_UPDATE_CHECKING=1'
      - 'RUST_UPDATE_BRANCH=public'
      - 'RUST_START_MODE=0'
      - 'RUST_OXIDE_ENABLED=0'
      - 'RUST_OXIDE_UPDATE_ON_BOOT=1'
      - 'RUST_SERVER_WORLDSIZE=3500'
      - 'RUST_SERVER_MAXPLAYERS=500'
      - 'RUST_SERVER_SAVE_INTERVAL=600'
    restart: unless-stopped

volumes:
  rust_data:
    external: false
```
