### ISSUE TITLE
Server fails fails to show in master list

### ISSUE THREAD

**Issue by thenetimp** [Didstopia/rust-server#48]
Server starts, connection via console works, but fails to show on master list.

I am using this docker-compose file, thoughts on what the problem might be?

```
version: '3'

services:
  rust:
    image: didstopia/rust-server
    container_name: rust
    ports:
      - 28015:28015
      - 28015:28015/udp
      - 28016:28016
    volumes:
      - /Rust:/steamcmd/rust
    environment:
      - 'CPU_MHZ=2199'
      - 'RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load +server.secure 1'
      - 'RUST_SERVER_NAME=Rusty Underpants Singapore'
      - 'RUST_SERVER_IDENTITY=docker'
      - 'RUST_SERVER_DESCRIPTION=Testing Traffic costs, come play while the server is up!'
      - 'RUST_SERVER_MAXPLAYERS=100'
      - 'RUST_SERVER_WORLDSIZE=3500'
      - 'RUST_SERVER_SEED=78476576'
      - 'RUST_RCON_WEB=1'
      - 'RUST_RCON_PORT=28016'
      - 'RUST_RCON_PASSWORD=testing12345'
      - 'RUST_UPDATE_CHECKING=1'
      - 'RUST_UPDATE_BRANCH=public'
      - 'RUST_START_MODE=2'
      - 'RUST_SERVER_SAVE_INTERVAL=600'
    restart: unless-stopped
```

**Comment by thenetimp** [comment]
I solved the problem.  I had left  RUST_SERVER_BANNER_URL commented out because I didn't want to define a banner, and that broke the command line interface.  Honestly I'd love to be able to NOT have all of these here, but instead, have them in the rust server.cfg file.

**Comment by thenetimp** [comment]
re-opened,  it's not fixed.  I thought it was because battlemetrics could see it

**Comment by thenetimp** [comment]
From my laptop.

Port Scan has started…
Port Scanning host: 167.71.202.8
	 Open TCP Port: 	28016
Port Scan has completed…

So for some reason 28015 isn't seen from the outside world.  even though there is no firewall, and even though I can connect to the game.  I am a bit confused.

**Comment by Dids** [comment]
This is a fairly common issue, and is usually due to other network or firewall configuration issues unrelated to Docker.

First off, what's the output from the server when it's running/startup has completed?

Secondly, where is this running? A hosted server? Dedicated or a VPS? Which provider?

**Comment by thenetimp** [comment]
Further investigation running a portscan locally shows it's ok (i think), but all port scans from the outside say 28015 is blocked.  So this may not be an issue with the container, I need to figure out how to debug this further.

tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      740/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1205/sshd
tcp        0      0 127.0.0.1:44065         0.0.0.0:*               LISTEN      2583/containerd
tcp6       0      0 :::28015                :::*                    LISTEN      31811/docker-proxy
tcp6       0      0 :::28016                :::*                    LISTEN      31797/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1205/sshd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           740/systemd-resolve
udp6       0      0 :::28015                :::*                                31825/docker-proxy

**Comment by thenetimp** [comment]
It's on a Digital Ocean Droplet that I started up last night.  Ubuntu 18.04LTS

```
rust    | SteamServer Initialized
rust    | Server startup complete
rust    | Resetting
rust    | Resetting
rust    | SteamServer Connected
rust    | BradleyAPC Spawned at :(-801.1, 24.1, 694.1)
rust    | Checking for new Steam Item Definitions...

rust    | 07/01/2019 10:21:48|Fatal|<>c__DisplayClass6.<receiveRequest>b__5|WebSocketSharp.WebSocketException: An exception has occurred while reading an HTTP request/response. ---> System.IO.EndOfStreamException: The header cannot be read from the data source.
rust    |                             at WebSocketSharp.HttpBase+<>c__DisplayClass1.<readHeaders>b__0 (System.Int32 i) [0x0000c] in <e43fdf6d91f44d8ea7f975577024882c>:0
rust    |                             at WebSocketSharp.Ext.EqualsWith (System.Int32 value, System.Char c, System.Action`1[T] action) [0x00001] in <e43fdf6d91f44d8ea7f975577024882c>:0
rust    |                             at WebSocketSharp.HttpBase.readHeaders (System.IO.Stream stream, System.Int32 maxLength) [0x00031] in <e43fdf6d91f44d8ea7f975577024882c>:0
rust    |                             at WebSocketSharp.HttpBase.Read[T] (System.IO.Stream stream, System.Func`2[T,TResult] parser, System.Int32 millisecondsTimeout) [0x00039] in <e43fdf6d91f44d8ea7f975577024882c>:0
rust    |                              --- End of inner exception stack trace ---
rust    |                             at WebSocketSharp.HttpBase.Read[T] (System.IO.Stream stream, System.Func`2[T,TResult] parser, System.Int32 millisecondsTimeout) [0x000ef] in <e43fdf6d91f44d8ea7f975577024882c>:0
```

Those are the last lines when I started it an hour or so ago.  It's still running now  <F1> then "connect 167.71.202.8:28015"  and the server connects, to me it's weird that the server connects even though the portscan shows the port as not being open.

**Comment by thenetimp** [comment]
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.28.0.2           tcp dpt:28016
ACCEPT     tcp  --  anywhere             172.28.0.2           tcp dpt:28015
ACCEPT     udp  --  anywhere             172.28.0.2           udp dpt:28015

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

I don't see anything wrong here, but I'm not a network expert.

**Comment by Dids** [comment]
Try the following, which forcibly binds the ports directly to the host:

```yaml
    ports:
      - target: 27016
        published: 27016
        protocol: tcp
        mode: host
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
```
